### ISSUE TITLE
Please make http-broadcast compatible with mercure 0.10

### ISSUE THREAD

**Issue by Yggdrasil** [jderusse/http-broadcast#32]
Hi, it appears Mercure 0.10 has a number of changes that will probably affect http-broadcast. See https://mercure.rocks/docs/UPGRADE

Since Mercure 0.10 adds support for Prometheus metrics we'd love to upgrade to it.

Would it be possible to update http-broadcast to work with this newer version?

**Comment by jderusse** [comment]
I just give a try with `dunglas/mercure:v0.10` and didn't get any inssue.

Do you have a specific error?
